# Generated by Codex on 2026-03-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riskcore", "0002_saccojoinrequest_loan_approved_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="purpose",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="loan",
            name="repayment_frequency",
            field=models.CharField(default="monthly", max_length=30),
        ),
        migrations.AddField(
            model_name="sacco",
            name="base_interest_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="sacco",
            name="benefits",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sacco",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sacco",
            name="membership_requirements",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sacco",
            name="terms_of_service",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="savingstransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="guarantorrelationship",
            constraint=models.UniqueConstraint(
                fields=("loan", "guarantor"),
                name="unique_guarantor_per_loan",
            ),
        ),
    ]
